CREATE TABLE IF NOT EXISTS "tag_adjustments" (
	"id" serial PRIMARY KEY NOT NULL,
	"player_id" integer NOT NULL,
	"tag_id" integer NOT NULL,
	"effective_date" date NOT NULL,
	"note" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "tag_holders" ALTER COLUMN "since" SET DATA TYPE date;--> statement-breakpoint
ALTER TABLE "tag_holders" ALTER COLUMN "since" DROP DEFAULT;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "tag_adjustments" ADD CONSTRAINT "tag_adjustments_player_id_players_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."players"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "tag_adjustments" ADD CONSTRAINT "tag_adjustments_tag_id_tags_id_fk" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
-- Hand-written data step, not generated by drizzle-kit.
--
-- tag_holders is about to stop being authoritative and start being derived
-- from the event log. Everything currently in it that no recorded round
-- explains — the league's original tag issue, players who joined before the
-- app existed, corrections made by hand — has to enter the log as an
-- adjustment or the first replay would simply lose it.
--
-- Dated at the beginning of time so these are the FLOOR of history and nothing
-- more: every recorded round outranks them, which is what makes standings
-- genuinely derived rather than anchored to whatever the table happened to say
-- on migration day. The cost is that this recomputes current standings from
-- full history and can move them wherever the record and reality have drifted.
-- Run `npm run tags:replay -- --dry-run` against a copy of prod and read the
-- diff BEFORE deploying this.
INSERT INTO "tag_adjustments" ("player_id", "tag_id", "effective_date", "note")
SELECT "player_id", "tag_id", DATE '1970-01-01', 'Held before tag history was replayed'
FROM "tag_holders";
